language: generic
services:
- docker
script:
- docker build --no-cache --pull -t wisvch/symposium-2022:$TRAVIS_BUILD_NUMBER .
after_success:
- if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == "main" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push wisvch/symposium-2022:$TRAVIS_BUILD_NUMBER;
  fi
notifications:
  email: false
